In [2]:
import torch
import torch.nn as nn
import random
import cv2
import matplotlib.pyplot as plt
import numpy as np
import sys
sys.path.insert(0, "/home/nguyen.thanh.huyenb/yolov7/")

In [3]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

In [4]:
from models.experimental import attempt_load
weights = "/home/nguyen.thanh.huyenb/yolov7/YOLOv7_test_semi/base_weights/epoch_03.pt"
weights = "/home/nguyen.thanh.huyenb/yolov7/YOLOv7/fold_2_percent_10_semi2/weights/epoch_009.pt"
model = attempt_load(weights, map_location=device) 
model.eval()

Fusing layers... 
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
IDetect.fuse


/home/nguyen.thanh.huyenb/miniconda3/envs/yolo/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


Model(
  (model): Sequential(
    (0): Conv(
      (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (act): SiLU(inplace=True)
    )
    (1): Conv(
      (conv): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (act): SiLU(inplace=True)
    )
    (2): Conv(
      (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (act): SiLU(inplace=True)
    )
    (3): Conv(
      (conv): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (act): SiLU(inplace=True)
    )
    (4): Conv(
      (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1))
      (act): SiLU(inplace=True)
    )
    (5): Conv(
      (conv): Conv2d(128, 64, kernel_size=(1, 1), stride=(1, 1))
      (act): SiLU(inplace=True)
    )
    (6): Conv(
      (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (act): SiLU(inplace=True)
    )
    (7): Conv(
      (conv): Conv2d(64, 64, kernel_size=(3, 3), strid

In [5]:
stride = int(model.stride.max()) 
stride
names = model.module.names if hasattr(model, 'module') else model.names
colors = [[random.randint(0, 255) for _ in range(3)] for _ in names]
names, colors

(['polyp'], [[100, 160, 42]])

In [6]:
model.gr

1.0

## Load image

In [7]:
from utils.datasets import letterbox
from utils.general import scale_coords, non_max_suppression
from utils.semi_psuedo_label_process import non_max_suppression_pseudo_decouple, non_max_suppression_pseudo_decouple_multi_view, xyxy2xywhn


In [8]:
# 3_244, 160,
paths = ['/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/12303.jpg', '/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/22037.jpg', '/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/16006.jpg', '/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/13021.jpg', '/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/22438.jpg', '/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/21530.jpg', '/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/5966.jpg', '/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/11259.jpg', '/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/19036.jpg', '/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/14941.jpg', '/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/14393.jpg', '/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/2714.jpg', '/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/8063.jpg', '/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/2500.jpg', '/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/28623.jpg', '/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/1564.jpg']

In [9]:
image_path = "/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/valid/images/161.jpg"
# image_path = path[3]
# image_path = "/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/images/1564.jpg"
# image_path = paths[-1]
print(image_path)
image0 = cv2.imread(image_path)
image0.shape
image0

/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/valid/images/161.jpg


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [10]:
image = letterbox(image0, (640, 640), stride=stride)[0]
image = image[:, :, ::-1].transpose(2, 0, 1)  # BGR to RGB, to 3x416x416
image = np.ascontiguousarray(image)
image.shape

(3, 480, 640)

In [11]:
image = torch.from_numpy(image).to(device).float()
image /= 255.0
image = image.unsqueeze(0)
image

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]]], device='cuda:0')

In [12]:
with torch.no_grad():   # Calculating gradients would cause a GPU memory leak
    out = model(image)
out[0].shape

torch.Size([1, 18900, 6])

In [13]:
pred = non_max_suppression(out[0], conf_thres=0.01)
pred

[tensor([[293.34180, 362.02612, 379.13074, 421.78699,   0.83138,   0.00000]], device='cuda:0')]

In [14]:
det = pred[0]
det[:, :4] = scale_coords(image.shape[2:], det[:, :4], image0.shape).round()
det

tensor([[352.00000, 434.00000, 455.00000, 506.00000,   0.83138,   0.00000]], device='cuda:0')

In [15]:
for *xyxy, conf, cls in reversed(det):
    # print(xyxy)
    label = f'{names[int(cls)]} {conf:.2f}'
    print(label)

polyp 0.83


In [16]:
image_path = image_path
label_dict = {
    0: "polyp"
}
image0 = cv2.imread(image_path)
for *xyxy, conf, cls in reversed(det):
    # Convert xyxy format to xywh format
    xyxy = [int(i.cpu()) for i in xyxy]
    x, y, w, h =  xyxy[0], xyxy[1], xyxy[2]-xyxy[0], xyxy[3]-xyxy[1]

    # Draw the bounding box on the image
    image0 = cv2.rectangle(image0, (x, y), (x+w, y+h), (0, 255, 0), 2)
    text = f"{names[int(cls)]}: {conf:.2f}"
    image0 = cv2.putText(image0, text, (x, y-5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
image0.shape
cv2.imwrite("out.png", image0)

True

In [17]:
cv2.imwrite("out.png", image0)

True

## Dataloader

In [18]:
from utils.datasets import create_dataloader
from utils.datasets import LoadImagesAndLabels
from utils.datasets_semi import LoadImagesAndLabelsSemi
from utils.plots import plot_images
import yaml
from utils.general import check_img_size
import os

In [19]:
path = "/home/nguyen.thanh.huyenb/PolypsSet/Semi_PolypsSet/semi_1_labels_fold_2_percent_10/train2019.2@10-unlabeled.json"
img_size = [640,640]
rect = False
batch_size = 16
augment=True
cache=False
pad=0.0
rect=False
stride=32             
rank=-1
world_size=1
workers=8
image_weights=False
quad=False
prefix=''
gs = stride = 32
imgsz,imgsz_test = [check_img_size(x, gs) for x in img_size]
imgsz,imgsz_test

(640, 640)

In [20]:
def load_hyperparameter(hyp_path):
        """Hyperparameters"""
        with open(hyp_path) as f:
            hyp = yaml.load(f, Loader=yaml.SafeLoader)
        return hyp
hyp = load_hyperparameter("/home/nguyen.thanh.huyenb/yolov7/data/hyp.scratch.p5.yaml")
hyp["mosaic"] = 0

In [21]:
dataset = LoadImagesAndLabelsSemi(path, imgsz, batch_size,
                                      augment=True,  # augment images
                                      hyp=hyp,  # augmentation hyperparameters
                                      rect=rect,  # rectangular training
                                      cache_images=cache,
                                      single_cls=True,
                                      stride=int(stride),
                                      pad=pad,
                                      mosaic=True,
                                      image_weights=image_weights,
                                      prefix=prefix)

loading annotations into memory...
Done (t=0.08s)
creating index...
index created!
/home/nguyen.thanh.huyenb/PolypsSet/PolypsSet/train2019/labels/1.txt
/home/nguyen.thanh.huyenb/PolypsSet/Semi_PolypsSet/semi_1_labels_fold_2_percent_10/train2019.2@10-unlabeled.json
/home/nguyen.thanh.huyenb/PolypsSet/Semi_PolypsSet/semi_1_labels_fold_2_percent_10/train2019.2@10-unlabeled.cache


Scanning '/home/nguyen.thanh.huyenb/PolypsSet/Semi_PolypsSet/semi_1_labels_fold_2_percent_10/train2019.2@10-unlabeled.cache' images and labels... 26015 found, 0 missing, 1540 empty, 0 corrupted: 100%|██████████| 26015/26015 [00:00<?, ?it/s]


In [22]:
from utils.datasets import InfiniteDataLoader

batch_size = min(batch_size, len(dataset))
nw = min([os.cpu_count() // world_size, batch_size if batch_size > 1 else 0, workers])  # number of workers
sampler = torch.utils.data.distributed.DistributedSampler(dataset) if rank != -1 else None
loader = torch.utils.data.DataLoader if image_weights else InfiniteDataLoader
# Use torch.utils.data.DataLoader() if dataset.properties will update during training else InfiniteDataLoader()
dataloader = loader(dataset,
                    batch_size=batch_size,
                    num_workers=nw,
                    sampler=sampler,
                    pin_memory=True,
                    shuffle=True,
                    collate_fn=LoadImagesAndLabelsSemi.collate_fn4 if quad else LoadImagesAndLabelsSemi.collate_fn)

In [23]:
# img, labels_out, path, shapes =  next(iter(dataloader))
label_imgs, label_targets, path, shape =  next(iter(dataloader))
(img, img_strong) = label_imgs 
labels_out = label_targets
plot_images(img, labels_out, path, "images.jpg")
labels_out, path

(tensor([[ 0.00000,  0.00000,  0.67847,  0.65807,  0.17242,  0.17764],
         [ 1.00000,  0.00000,  0.23564,  0.51939,  0.46703,  0.42998],
         [ 2.00000,  0.00000,  0.18721,  0.55771,  0.37442,  0.54323],
         [ 3.00000,  0.00000,  0.53183,  0.49787,  0.26257,  0.22502],
         [ 4.00000,  0.00000,  0.47499,  0.53946,  0.26933,  0.27127],
         [ 5.00000,  0.00000,  0.48888,  0.64358,  0.22598,  0.22591],
         [ 6.00000,  0.00000,  0.26915,  0.46326,  0.53830,  0.64124],
         [ 7.00000,  0.00000,  0.70232,  0.44550,  0.27623,  0.31850],
         [ 8.00000,  0.00000,  0.80252,  0.66096,  0.22008,  0.21917],
         [ 9.00000,  0.00000,  0.53428,  0.51797,  0.14823,  0.12379],
         [10.00000,  0.00000,  0.69080,  0.70206,  0.32845,  0.28692],
         [11.00000,  0.00000,  0.33760,  0.39679,  0.39576,  0.35828],
         [12.00000,  0.00000,  0.27591,  0.51140,  0.20563,  0.20351],
         [13.00000,  0.00000,  0.30762,  0.59206,  0.37754,  0.33073],
      

In [24]:
img

tensor([[[[114, 114, 114,  ..., 114, 114, 114],
          [114, 114, 114,  ..., 114, 114, 114],
          [114, 114, 114,  ..., 114, 114, 114],
          ...,
          [114, 114, 114,  ...,   1,   0,   0],
          [114, 114, 114,  ...,   1,   0,   0],
          [114, 114, 114,  ...,   0,   0,   0]],

         [[114, 114, 114,  ..., 114, 114, 114],
          [114, 114, 114,  ..., 114, 114, 114],
          [114, 114, 114,  ..., 114, 114, 114],
          ...,
          [114, 114, 114,  ...,   1,   0,   0],
          [114, 114, 114,  ...,   1,   0,   0],
          [114, 114, 114,  ...,   0,   0,   0]],

         [[114, 114, 114,  ..., 114, 114, 114],
          [114, 114, 114,  ..., 114, 114, 114],
          [114, 114, 114,  ..., 114, 114, 114],
          ...,
          [114, 114, 114,  ...,   1,   0,   0],
          [114, 114, 114,  ...,   1,   0,   0],
          [114, 114, 114,  ...,   0,   0,   0]]],


        [[[114, 114, 114,  ..., 114, 114, 114],
          [114, 114, 114,  ..., 114

In [25]:
img = img.float()

img /= 255
img

tensor([[[[0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          [0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          [0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          ...,
          [0.44706, 0.44706, 0.44706,  ..., 0.00392, 0.00000, 0.00000],
          [0.44706, 0.44706, 0.44706,  ..., 0.00392, 0.00000, 0.00000],
          [0.44706, 0.44706, 0.44706,  ..., 0.00000, 0.00000, 0.00000]],

         [[0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          [0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          [0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          ...,
          [0.44706, 0.44706, 0.44706,  ..., 0.00392, 0.00000, 0.00000],
          [0.44706, 0.44706, 0.44706,  ..., 0.00392, 0.00000, 0.00000],
          [0.44706, 0.44706, 0.44706,  ..., 0.00000, 0.00000, 0.00000]],

         [[0.44706, 0.44706, 0.44706,  ..., 0.44706, 0.44706, 0.44706],
          [0.44706, 0.44706, 0

In [38]:
with torch.no_grad():   # Calculating gradients would cause a GPU memory leak
    out = model(img.to(device))
out[0].shape

torch.Size([16, 25200, 6])

In [39]:
out[1][0].shape, out[1][1].shape, out[1][2].shape

(torch.Size([16, 3, 80, 80, 6]),
 torch.Size([16, 3, 40, 40, 6]),
 torch.Size([16, 3, 20, 20, 6]))

In [40]:
3*80*80 , 3*40*40 , 3*20*20

(19200, 4800, 1200)

In [41]:
pred = non_max_suppression(out[0][:, : , :] ,conf_thres=0.25, iou_thres=0.5)
pred

[tensor([[373.96167, 363.33322, 493.80249, 483.78085,   0.95230,   0.00000]], device='cuda:0'),
 tensor([[ 13.39743, 200.69562, 293.64038, 460.66107,   0.93433,   0.00000]], device='cuda:0'),
 tensor([[ 46.60094, 195.41460, 164.52548, 335.67969,   0.62974,   0.00000]], device='cuda:0'),
 tensor([[3.26337e+02, 1.10855e+00, 5.93722e+02, 6.40405e+02, 9.86246e-01, 0.00000e+00],
         [9.36274e+01, 1.31122e+00, 3.78615e+02, 6.38745e+02, 9.37050e-01, 0.00000e+00],
         [2.61640e+02, 2.29868e+02, 4.21485e+02, 4.12679e+02, 8.63989e-01, 0.00000e+00],
         [2.53581e+02, 7.07387e+01, 4.30781e+02, 5.67174e+02, 3.62440e-01, 0.00000e+00]], device='cuda:0'),
 tensor([[ 2.78490e+02, -2.15973e-01,  5.30787e+02,  6.39406e+02,  9.93248e-01,  0.00000e+00],
         [ 2.54534e+02,  4.05653e+02,  4.95120e+02,  6.41852e+02,  9.20979e-01,  0.00000e+00],
         [ 2.18476e+02,  2.19916e+02,  3.94103e+02,  4.86091e+02,  8.34105e-01,  0.00000e+00],
         [ 8.59593e+01,  7.60104e+00,  3.45731e+02, 

In [42]:
pred1, pred_cls = non_max_suppression_pseudo_decouple(out[0],conf_thres=0.25, iou_thres=0.45)
pred1, pred_cls

([tensor([[373.96167, 363.33322, 493.80249, 483.78085,   0.93452,   0.00000]], device='cuda:0'),
  tensor([[ 13.39743, 200.69562, 293.64038, 460.66107,   0.92018,   0.00000]], device='cuda:0'),
  tensor([[ 46.60094, 195.41460, 164.52548, 335.67969,   0.61957,   0.00000]], device='cuda:0'),
  tensor([[3.27029e+02, 1.23019e+00, 5.93698e+02, 6.39625e+02, 9.73663e-01, 0.00000e+00],
          [9.36274e+01, 1.31122e+00, 3.78615e+02, 6.38745e+02, 9.26665e-01, 0.00000e+00],
          [2.61640e+02, 2.29868e+02, 4.21485e+02, 4.12679e+02, 8.49867e-01, 0.00000e+00],
          [2.53581e+02, 7.07387e+01, 4.30781e+02, 5.67174e+02, 3.56541e-01, 0.00000e+00]], device='cuda:0'),
  tensor([[2.82183e+02, 2.99072e-01, 5.30762e+02, 6.38039e+02, 9.78215e-01, 0.00000e+00],
          [2.54534e+02, 4.05653e+02, 4.95120e+02, 6.41852e+02, 9.04955e-01, 0.00000e+00],
          [2.18476e+02, 2.19916e+02, 3.94103e+02, 4.86091e+02, 8.19051e-01, 0.00000e+00],
          [8.59593e+01, 7.60104e+00, 3.45731e+02, 6.32548e+0

In [43]:
from utils.general import xyxy2xywh
from copy import deepcopy
def convert_output_to_label(imgs, preds, shapes):
    labels = torch.zeros(0, 7).to(device)
   
    for i, pred in enumerate(preds):
        label = torch.zeros(len(pred), 7).to(device)
        h0, w0  = shapes[i][0]
        box = scale_coords(imgs[i].shape[:2], pred[:, 0:4], shape[i][0], shape[i][1]).round()
        box = xyxy2xywhn(pred[:, 0:4], w0, h0)
        label[:, 0] = i
        label[:, 1] = pred[:, 5]
        label[:, 2:6] = box
        label[:, 6] = pred[:, 4]
        labels = torch.cat([labels, label])
    
    return labels

pseudo_label = convert_output_to_label(img, pred, shape)
pseudo_label,  labels_out

(tensor([[ 0.00000,  0.00000,  0.67794,  0.71574,  0.18725,  0.25093,  0.95230],
         [ 1.00000,  0.00000,  0.23990,  0.52026,  0.43793,  0.49329,  0.93433],
         [ 2.00000,  0.00000,  0.16494,  0.38656,  0.18426,  0.29222,  0.62974],
         [ 3.00000,  0.00000,  0.71969,  0.50000,  0.41831,  1.00000,  0.98625],
         [ 3.00000,  0.00000,  0.36940,  0.50000,  0.44585,  1.00000,  0.93705],
         [ 3.00000,  0.00000,  0.53435,  0.50254,  0.25007,  0.36489,  0.86399],
         [ 3.00000,  0.00000,  0.53532,  0.49792,  0.27722,  0.99089,  0.36244],
         [ 4.00000,  0.00000,  0.63232,  0.50000,  0.39426,  1.00000,  0.99325],
         [ 4.00000,  0.00000,  0.58573,  0.83126,  0.37596,  0.33747,  0.92098],
         [ 4.00000,  0.00000,  0.47863,  0.56263,  0.27445,  0.50508,  0.83411],
         [ 4.00000,  0.00000,  0.33730,  0.50000,  0.40594,  1.00000,  0.51644],
         [ 5.00000,  0.00000,  0.49325,  0.67137,  0.25475,  0.33019,  0.94196],
         [ 6.00000,  0.00000

In [44]:
pseudo_label1 = convert_output_to_label(img, pred, shape)
pseudo_label1

tensor([[ 0.00000,  0.00000,  0.40676,  0.26278,  0.11235,  0.15056,  0.95230],
        [ 1.00000,  0.00000,  0.20394,  0.33506,  0.37228,  0.41935,  0.93433],
        [ 2.00000,  0.00000,  0.09897,  0.07647,  0.11055,  0.15293,  0.62974],
        [ 3.00000,  0.00000,  0.66654,  0.39371,  0.38741,  0.78743,  0.98625],
        [ 3.00000,  0.00000,  0.34212,  0.39371,  0.41292,  0.78743,  0.93705],
        [ 3.00000,  0.00000,  0.49489,  0.32671,  0.23160,  0.33794,  0.86399],
        [ 3.00000,  0.00000,  0.49579,  0.39064,  0.25674,  0.78128,  0.36244],
        [ 4.00000,  0.00000,  0.53753,  0.37144,  0.33516,  0.74288,  0.99325],
        [ 4.00000,  0.00000,  0.49793,  0.59944,  0.31960,  0.28688,  0.92098],
        [ 4.00000,  0.00000,  0.40688,  0.37107,  0.23331,  0.42936,  0.83411],
        [ 4.00000,  0.00000,  0.28673,  0.37144,  0.34509,  0.74288,  0.51644],
        [ 5.00000,  0.00000,  0.45682,  0.48307,  0.23594,  0.30581,  0.94196],
        [ 6.00000,  0.00000,  0.14489,  

In [45]:
plot_images(deepcopy(img), pseudo_label, path, "images_out.jpg")
plot_images(deepcopy(img), pseudo_label1, path, "images_out1.jpg")
plot_images(deepcopy(img), labels_out, path, "images_label.jpg")


array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [220, 220, 220],
        [185, 185, 185],
        ...,
        [185, 185, 185],
        [185, 185, 185],
        [255, 255, 255]],

       [[255, 255, 255],
        [185, 185, 185],
        [114, 114, 114],
        ...,
        [114, 114, 114],
        [114, 114, 114],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [185, 185, 185],
        [114, 114, 114],
        ...,
        [114, 114, 114],
        [114, 114, 114],
        [255, 255, 255]],

       [[255, 255, 255],
        [185, 185, 185],
        [114, 114, 114],
        ...,
        [114, 114, 114],
        [114, 114, 114],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]